[package]
edition = "2024"
name = "ylab-stm32"
version = "0.2.0"
license = "MIT OR Apache-2.0"
#resolver = "2"

[lib]
name = "ylab_stm32"
path = "src/mod.rs"

[features]
f446ze = [
    "embassy-stm32/defmt",
    "embassy-stm32/stm32f446ze",
    "embassy-stm32/memory-x",
    "embassy-stm32/time-driver-any",
    "embassy-stm32/exti",
]
f446re = [
    "embassy-stm32/defmt",
    "embassy-stm32/stm32f446re",
    "embassy-stm32/memory-x",
    "embassy-stm32/time-driver-any",
    "embassy-stm32/exti",
]
h742zi = [
    "embassy-stm32/defmt",
    "embassy-stm32/stm32h743zi",
    "embassy-stm32/memory-x",
    "embassy-stm32/time-driver-any",
    "embassy-stm32/exti",
]
default = []

[dependencies]
ylab-lib = { path = "../ylab-lib" }
cortex-m = { version = "0.7.7", features = [
    "inline-asm",
    "critical-section-single-core",
] }
cortex-m-rt = "0.7.5"

defmt = "1.0.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

embassy-stm32 = "0.4.0" #{ version = "0.4.0", features = []}
embassy-executor = { version = "0.9.1", features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
] }

embassy-sync = { version = "0.7.2", features = ["defmt"] }
embassy-embedded-hal = { version = "0.5.0", features = ["defmt"] }
